import RollHelper from "./RollHelper";

export interface Devil {
  ghostTrait: string;
  ghostSecondaryEffect: string;
  type: { aspect: string; affinity: string };
  desires: string;
  summonedHorror: string;
  name: string;
  features: string;
}

export default class DevilHelper {
  public static formatDescription(devil: Devil) {
    return `<h3>Devil: ${devil.name}</h3><strong>Ghost Traits:</strong> ${devil.ghostTrait}<br><strong>Ghostly Secondary Effects:</strong> ${devil.ghostSecondaryEffect}<br><strong>Aspect:</strong> ${devil.type.aspect}<br><strong>Affinity: </strong>${devil.type.affinity}<br><strong>Desire:</strong> ${devil.desires}<br><strong>Summoned Horror:</strong>  ${devil.summonedHorror}<br><strong>Features:</strong> ${devil.features}`;
  }
  public static generateDevil() {
    return {
      ghostTrait: RollHelper.rollArray(this.ghostTrait),
      ghostSecondaryEffect: RollHelper.rollArray(this.ghostSecondaryEffect),
      type: RollHelper.rollArray(this.type),
      desires: RollHelper.rollArray(this.desire),
      summonedHorror: RollHelper.rollArray(this.summonedHorror),
      name: RollHelper.rollArray(this.names),
      features: RollHelper.rollArray(this.demonFeatures),
    } as Devil;
  }

  public static readonly ghostTrait = [
    "Jealous",
    "Desperate",
    "Violent",
    "Hysterical",
    "Skittish",
    "Fleeting",
    "Curious",
    "Deceptive",
    "Clever",
    "Probing",
    "Knowledgeable",
    "Charming",
    "Prophetic",
    "Insightful",
    "True",
    "Revelatory",
    "Guiding",
    "Instructive",
    "Reactive",
    "Territorial",
    "Dominant",
    "Insisitent",
    "Bold",
    "Demanding",
    "Angry",
    "Volatile",
    "Aggressive",
    "Wild",
    "Savage",
    "Vengeful",
    "Mad",
    "Chaotic",
    "Bizzare",
    "Destructive",
    "Insane",
    "Vile",
  ];

  public static readonly ghostSecondaryEffect = [
    "Frost, Chill",
    "Cold wind",
    "Faint visions of the local past",
    "Electrical discharge",
    "Weird shadows",
    "Faint echoes",
    "Frost, Chill",
    "Cold wind",
    "Faint visions of the local past",
    "Electrical discharge",
    "Weird shadows",
    "Faint echoes",
    "Frost, Chill",
    "Cold wind",
    "Faint visions of the local past",
    "Electrical discharge",
    "Weird shadows",
    "Faint echoes",
    "Mist, Fog",
    "Rushing wind",
    "Intense visual echoes",
    "Intense magnetism",
    "Disturbing shadows",
    "Thunderous sounds",
    "Mist, Fog",
    "Rushing wind",
    "Intense visual echoes",
    "Intense magnetism",
    "Disturbing shadows",
    "Thunderous sounds",
    "Freezing fog",
    "Storm winds",
    "Pitch darkness",
    "Lightning",
    "Clutching shadows",
    "Voices in your head",
  ];

  public static readonly type = [
    {
      aspect: "Humanoid with Bestial/Elemental Features",
      affinity: "Sea, Water",
    },
    {
      aspect: "Humanoid with Bestial/Elemental Features",
      affinity: "Darkness",
    },
    {
      aspect: "Humanoid with Bestial/Elemental Features",
      affinity: "Earth, Metal",
    },
    {
      aspect: "Humanoid with Bestial/Elemental Features",
      affinity: "Fire, Smoke",
    },
    {
      aspect: "Humanoid with Bestial/Elemental Features",
      affinity: "Sky, Stars",
    },
    {
      aspect: "Humanoid with Bestial/Elemental Features",
      affinity: "Storm, Wind",
    },
    { aspect: "Animal", affinity: "Sea, Water" },
    { aspect: "Animal", affinity: "Darkness" },
    { aspect: "Animal", affinity: "Earth, Metal" },
    { aspect: "Animal", affinity: "Fire, Smoke" },
    { aspect: "Animal", affinity: "Sky, Stars" },
    { aspect: "Animal", affinity: "Storm, Wind" },
    { aspect: "Monstrous", affinity: "Sea, Water" },
    { aspect: "Monstrous", affinity: "Darkness" },
    { aspect: "Monstrous", affinity: "Earth, Metal" },
    { aspect: "Monstrous", affinity: "Fire, Smoke" },
    { aspect: "Monstrous", affinity: "Sky, Stars" },
    { aspect: "Monstrous", affinity: "Storm, Wind" },
    { aspect: "Animal", affinity: "Sea, Water" },
    { aspect: "Animal", affinity: "Darkness" },
    { aspect: "Animal", affinity: "Earth, Metal" },
    { aspect: "Animal", affinity: "Fire, Smoke" },
    { aspect: "Animal", affinity: "Sky, Stars" },
    { aspect: "Animal", affinity: "Storm, Wind" },
  ];

  public static readonly desire = [
    "Mayhem",
    "Murder",
    "Justice",
    "Corruption",
    "Power",
    "Control",
    "Knowledge",
    "Pleasure",
    "Suffering",
    "War",
    "Revenge",
    "Chaos",
    "Freedom",
    "Savagery",
    "Manipulation",
    "Deception",
    "Fear",
    "Achievement",
  ];

  public static readonly summonedHorror = [
    "Reeking Tar",
    "Writhing Mass",
    "Radiant Being",
    "Crystalline Shards",
    "Creeping Growth",
    "Animated Stone",
    "Couds of Burning Ash",
    "Shadow Being",
    "Swarm of Insects",
    "Toxic Cloud",
    "Feiry Being",
    "Liquid Being",
    "Flayed Being",
    "Shambling Rags",
    "Freezing Fire",
    "Impossible Geometry",
    "Monstrous Animal",
    "Shimmering Spheres",
    "Twisting Machinery",
    "Psychic Mist",
    "Throbbing Viscera",
    "Metallic Being",
    "Coil of Thorns",
    "Hypnotic Lights",
    "Oozing Slug",
    "Tremulous Vibrations",
    "Lashing Hooks",
    "Skeleton of Black Glass",
    "Flowing Quicksilver",
    "Clutching Darkness",
    "Floating Octopoid",
    "Cloying Vapors",
    "Swirling Mucus",
    "Serpent Being",
    "Insectoid Being",
    "Consuming Orb",
  ];

  public static readonly names = [
    "Korvaeth",
    "Sevraxis",
    "Argaz",
    "Zalvroxos",
    "Kethtera",
    "Arkeveron",
    "Ixis",
    "Kyronax",
    "Voldranai",
    "Esketra",
    "Ardranax",
    "Kylastra",
    "Oryxus",
    "Ahazu",
    "Tyraxis",
    "Azarax",
    "Vaskari",
  ];

  public static readonly demonFeatures = [
    "Black Shark Eyes",
    "Onyx Scales",
    "Iridescent Scales",
    "Crystalline Scales",
    "Metallic Scales",
    "Razor-Sharp Claws",
    "Bony Protrusions",
    "Multiple Eyes",
    "Lashing Tail",
    "Leathery Wings",
    "Spines",
    "Dripping Ichor",
    "Glowing Eyes",
    "Glowing Markings",
    "Hair or Fur Drifting as if Underwater",
    "Hair or Fur Burning With a Cold Fire",
    "Feathers",
    "Multiple Arms",
    "Hard Shell",
    "Metallic Plates",
    "Lights Dim",
    "Lights Flare",
    "Plants Wither",
    "Plants Grow Wildly",
    "Mechanisms Grind to a Halt",
    "Liquid Freezes",
    "Liquid Boils",
    "Liquid Turns to Blood",
    "Liquid Turns to Ash",
  ];
}
